### ISSUE TITLE
352air PM2.5 for HA

### ISSUE THREAD

**Issue by WalterDSU** [mckelvin/homebridge-352air#3]
does it work in home-assistant? I got one of these, but no way to add it into Hass. can you help??

**Comment by mckelvin** [comment]
Hey @WalterDSU , this plugin is only for homebridge but you can port it as a home-assistant plugin. You can read the logic [here](https://github.com/mckelvin/homebridge-352air/blob/master/index.js). Basically the device broadcasts the stats periodically. You need to start a UDP server to capture and deserialize the broadcasted message.
